#statistical analysis
mean(airquality$Temp)
mean(airquality$Wind)
mean(airquality$Month)
mean(airquality$Day)
median(airquality$Temp)
median(airquality$Wind)
median(airquality$Month)
median(airquality$Day)
min(airquality$Wind)
min(airquality$Temp)
min(airquality$Month)
min(airquality$Day)
max(airquality$Wind)
max(airquality$Temp)
max(airquality$Month)
max(airquality$Day)
quantile(airquality$Wind,c(0.75))
quantile(airquality$Temp,c(0.75))
quantile(airquality$Month,c(0.75))
quantile(airquality$Day,c(0.75))
quantile(airquality$Wind)
quantile(airquality$Temp)
quantile(airquality$Month)
quantile(airquality$Day)
var(airquality$Wind)
var(airquality$Temp)
var(airquality$Month)
var(airquality$Day)
sd(airquality$Wind)
sd(airquality$Temp)
sd(airquality$Month)
sd(airquality$Day)
summary(airquality)






